export const INTENTS = Object.freeze({
  AFILIACION_IMSS: "AFILIACION_IMSS", SERVICIO_MEDICO: "SERVICIO_MEDICO", COTIZACION: "COTIZACION", COTIZACION_SEMANAS: "COTIZACION_SEMANAS",
  REACTIVACION_IMSS: "REACTIVACION_IMSS", BAJA_IMSS: "BAJA_IMSS", CONSULTA_SEMANAS: "CONSULTA_SEMANAS",
  PENSION: "PENSION", LEY_73: "LEY_73", LEY_97: "LEY_97", AFORE_GENERAL: "AFORE_GENERAL",
  CAMBIO_AFORE: "CAMBIO_AFORE", RETIRO_AFORE: "RETIRO_AFORE", RETIRO_AFORE_FALLECIMIENTO: "RETIRO_AFORE_FALLECIMIENTO",
  VIUDEZ: "VIUDEZ", ORFANDAD: "ORFANDAD", BENEFICIARIOS: "BENEFICIARIOS", INFONAVIT: "INFONAVIT",
  EMBARAZO: "EMBARAZO", INCAPACIDAD: "INCAPACIDAD", NSS: "NSS", CURP: "CURP", DOCUMENTOS: "DOCUMENTOS",
  PAGO: "PAGO", LLAMADA: "LLAMADA", CITA: "CITA", SEGUIMIENTO: "SEGUIMIENTO", QUEJA: "QUEJA",
  PROVEEDOR: "PROVEEDOR", CONFIANZA_EMPRESA: "CONFIANZA_EMPRESA", INFORMACION_GENERAL: "INFORMACION_GENERAL", OTRO: "OTRO"
});

export const INTENT_META = Object.freeze({
  [INTENTS.AFILIACION_IMSS]: { label: "Afiliación al IMSS", family: "comercial", priority: "normal" },
  [INTENTS.SERVICIO_MEDICO]: { label: "Servicio médico", family: "comercial", priority: "normal" },
  [INTENTS.COTIZACION]: { label: "Cotización", family: "comercial", priority: "normal" },
  [INTENTS.COTIZACION_SEMANAS]: { label: "Cotización para completar semanas", family: "pension", priority: "alta" },
  [INTENTS.REACTIVACION_IMSS]: { label: "Reactivación IMSS", family: "comercial", priority: "normal" },
  [INTENTS.BAJA_IMSS]: { label: "Baja del IMSS", family: "orientacion", priority: "normal" },
  [INTENTS.CONSULTA_SEMANAS]: { label: "Consulta de semanas", family: "pension", priority: "normal" },
  [INTENTS.PENSION]: { label: "Pensión", family: "pension", priority: "normal" },
  [INTENTS.LEY_73]: { label: "Ley 73", family: "pension", priority: "normal" },
  [INTENTS.LEY_97]: { label: "Ley 97", family: "pension", priority: "normal" },
  [INTENTS.AFORE_GENERAL]: { label: "AFORE", family: "afore", priority: "normal" },
  [INTENTS.CAMBIO_AFORE]: { label: "Cambio de AFORE", family: "afore", priority: "normal" },
  [INTENTS.RETIRO_AFORE]: { label: "Retiro de AFORE", family: "afore", priority: "alta" },
  [INTENTS.RETIRO_AFORE_FALLECIMIENTO]: { label: "Retiro de AFORE por fallecimiento", family: "afore_fallecimiento", priority: "alta" },
  [INTENTS.VIUDEZ]: { label: "Pensión por viudez", family: "fallecimiento", priority: "alta" },
  [INTENTS.ORFANDAD]: { label: "Pensión por orfandad", family: "fallecimiento", priority: "alta" },
  [INTENTS.BENEFICIARIOS]: { label: "Beneficiarios", family: "orientacion", priority: "normal" },
  [INTENTS.INFONAVIT]: { label: "INFONAVIT", family: "comercial", priority: "normal" },
  [INTENTS.EMBARAZO]: { label: "Embarazo", family: "salud", priority: "alta" },
  [INTENTS.INCAPACIDAD]: { label: "Incapacidad", family: "orientacion", priority: "alta" },
  [INTENTS.NSS]: { label: "Consulta de NSS", family: "datos", priority: "normal" },
  [INTENTS.CURP]: { label: "CURP", family: "datos", priority: "normal" },
  [INTENTS.DOCUMENTOS]: { label: "Documentos", family: "datos", priority: "normal" },
  [INTENTS.PAGO]: { label: "Pago", family: "operacion", priority: "alta" },
  [INTENTS.LLAMADA]: { label: "Solicitud de llamada", family: "operacion", priority: "alta" },
  [INTENTS.CITA]: { label: "Cita", family: "operacion", priority: "normal" },
  [INTENTS.SEGUIMIENTO]: { label: "Seguimiento", family: "operacion", priority: "normal" },
  [INTENTS.QUEJA]: { label: "Queja", family: "servicio", priority: "alta" },
  [INTENTS.PROVEEDOR]: { label: "Proveedor o alianza", family: "b2b", priority: "alta" },
  [INTENTS.CONFIANZA_EMPRESA]: { label: "Validación y confianza de empresa", family: "confianza", priority: "alta" },
  [INTENTS.INFORMACION_GENERAL]: { label: "Información general", family: "general", priority: "normal" },
  [INTENTS.OTRO]: { label: "Otro", family: "general", priority: "normal" }
});
