import { INTENTS } from "./catalog.js";

export const INTENT_RULES = [
  { intent: INTENTS.RETIRO_AFORE_FALLECIMIENTO, weight: 10, all: [/afor[eé]/i, /(falleci[oó]|fallecimiento|muri[oó]|difunto)/i], evidence: "AFORE + fallecimiento" },
  { intent: INTENTS.RETIRO_AFORE_FALLECIMIENTO, weight: 9, all: [/(retirar|retiro|recuperar)/i, /(pap[aá]|mam[aá]|padre|madre|espos[oa]).*(falleci[oó]|muri[oó])/i], evidence: "Retiro por fallecimiento de familiar" },
  { intent: INTENTS.RETIRO_AFORE, weight: 7, all: [/(retirar|retiro|sacar|recuperar)/i, /afor[eé]/i], evidence: "Solicitud de retiro AFORE" },
  { intent: INTENTS.VIUDEZ, weight: 7, any: [/viudez/i, /pensi[oó]n.*(espos[oa]|viud[oa])/i], evidence: "Viudez" },
  { intent: INTENTS.ORFANDAD, weight: 7, any: [/orfandad/i, /pensi[oó]n.*(hijo|hija|menor)/i], evidence: "Orfandad" },
  { intent: INTENTS.EMBARAZO, weight: 7, any: [/embarazad[ao]/i, /embarazo/i, /parto/i, /maternidad/i], evidence: "Embarazo o maternidad" },
  { intent: INTENTS.INCAPACIDAD, weight: 6, any: [/incapacidad/i, /subsidio.*maternidad/i], evidence: "Incapacidad" },
  { intent: INTENTS.CONSULTA_SEMANAS, weight: 6, any: [/cu[aá]ntas semanas/i, /semanas cotizadas/i, /consultar.*semanas/i, /revisar.*semanas/i], evidence: "Consulta de semanas cotizadas" },
  { intent: INTENTS.LEY_73, weight: 7, any: [/ley\s*73/i, /r[eé]gimen\s*73/i], evidence: "Ley 73" },
  { intent: INTENTS.LEY_97, weight: 7, any: [/ley\s*97/i, /r[eé]gimen\s*97/i], evidence: "Ley 97" },
  { intent: INTENTS.PENSION, weight: 5, any: [/pensi[oó]n/i, /pensionarme/i, /jubilarme/i], evidence: "Pensión" },
  { intent: INTENTS.CAMBIO_AFORE, weight: 6, any: [/cambiar.*afor[eé]/i, /mover.*afor[eé]/i, /regresar.*(banamex|banco|afor[eé])/i], evidence: "Cambio de administradora AFORE" },
  { intent: INTENTS.AFORE_GENERAL, weight: 4, any: [/afor[eé]/i, /aportaciones.*afor[eé]/i], evidence: "AFORE" },
  { intent: INTENTS.INFONAVIT, weight: 5, any: [/infonavit/i, /puntos.*vivienda/i, /puntos.*infonavit/i], evidence: "INFONAVIT" },
  { intent: INTENTS.REACTIVACION_IMSS, weight: 6, any: [/reactivar/i, /volver a activar/i, /recuperar.*imss/i, /volver.*seguro/i], evidence: "Reactivación IMSS" },
  { intent: INTENTS.BAJA_IMSS, weight: 5, any: [/me dieron de baja/i, /baja.*imss/i, /dej[eé] de cotizar/i], evidence: "Baja IMSS" },
  { intent: INTENTS.SERVICIO_MEDICO, weight: 5, any: [/servicio m[eé]dico/i, /consultas m[eé]dicas/i, /atenci[oó]n m[eé]dica/i, /seguro m[eé]dico/i], evidence: "Servicio médico" },
  { intent: INTENTS.AFILIACION_IMSS, weight: 5, any: [/afiliarme/i, /afiliaci[oó]n.*imss/i, /darme de alta/i, /alta.*imss/i, /tener imss/i], evidence: "Afiliación al IMSS" },
  { intent: INTENTS.COTIZACION, weight: 4, any: [/cu[aá]nto cuesta/i, /precio/i, /cotizaci[oó]n/i, /cotizar/i, /mensualidad/i], evidence: "Cotización" },
  { intent: INTENTS.BENEFICIARIOS, weight: 4, any: [/beneficiari[oa]s?/i, /asegurar.*(hijo|hija|esposa|esposo|familia)/i], evidence: "Beneficiarios" },
  { intent: INTENTS.NSS, weight: 4, any: [/nss/i, /n[uú]mero de seguro social/i], evidence: "NSS" },
  { intent: INTENTS.CURP, weight: 3, any: [/curp/i], evidence: "CURP" },
  { intent: INTENTS.PAGO, weight: 5, any: [/ya pagu[eé]/i, /comprobante/i, /dep[oó]sito/i, /transferencia/i], evidence: "Pago o comprobante" },
  { intent: INTENTS.LLAMADA, weight: 5, any: [/ll[aá]mame/i, /pueden llamarme/i, /quiero una llamada/i, /hablar con un asesor/i], evidence: "Solicitud de llamada" },
  { intent: INTENTS.CITA, weight: 4, any: [/agendar/i, /cita/i, /horario.*llamada/i], evidence: "Cita" },
  { intent: INTENTS.SEGUIMIENTO, weight: 4, any: [/seguimiento/i, /c[oó]mo va mi tr[aá]mite/i, /estatus/i, /quedaron de llamarme/i], evidence: "Seguimiento" },
  { intent: INTENTS.QUEJA, weight: 6, any: [/queja/i, /no me respondieron/i, /me estafaron/i, /p[eé]simo servicio/i, /molest[oa]/i], evidence: "Queja o inconformidad" },
  { intent: INTENTS.PROVEEDOR, weight: 10, any: [/quiero vender/i, /vender las afiliaciones/i, /soy proveedor/i, /alianza comercial/i, /distribuidor/i, /comercializar afiliaciones/i, /trabajar con ustedes vendiendo/i], evidence: "Proveedor o alianza" },
  { intent: INTENTS.CONFIANZA_EMPRESA, weight: 9, any: [/d[oó]nde se (encuentran|ubican)/i, /d[oó]nde est[aá]n/i, /ubicaci[oó]n/i, /raz[oó]n social/i, /muchos estafadores/i, /es estafa/i, /es fraude/i, /son confiables/i, /oficinas?/i], evidence: "Validación de ubicación o confianza" },
  { intent: INTENTS.INFORMACION_GENERAL, weight: 2, any: [/informaci[oó]n/i, /quiero saber/i, /me interesa/i, /dudas?/i], evidence: "Solicitud general de información" }
];
