import fs from "node:fs";
import assert from "node:assert/strict";
const js=fs.readFileSync(new URL("../src/inspector/public/inspector.js",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/inspector/public/inspector.css",import.meta.url),"utf8");
assert.match(js,/closeAdvisorModal/);
assert.match(js,/data-remove-from-group/);
assert.match(js,/data-delete-master/);
assert.match(js,/agents\/remove/);
assert.match(css,/#advisorModal\{z-index:2200/);
assert.match(css,/modal-underlay/);
console.log("Inspector V1.5.1 modal/delete tests OK");
