import fs from "node:fs";
import assert from "node:assert/strict";
const js=fs.readFileSync(new URL("../src/inspector/public/inspector.js",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../src/inspector/public/inspector.css",import.meta.url),"utf8");
assert.match(js,/data-ops-tab/);
assert.match(js,/draggable="true"/);
assert.match(js,/data-agent-menu/);
assert.match(js,/openAddAdvisor/);
assert.match(js,/rotationSearch/);
assert.match(js,/dragstart/);
assert.match(css,/dynamic-agent-row/);
assert.match(css,/ops-tabs/);
console.log("Inspector V1.5 frontend tests OK");
