import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { SaleStore } from "../src/operations/sale-store.js";
import { SaleWorkflowEngine } from "../src/operations/workflow-engine.js";

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"martcom-validity-"));const store=new SaleStore(path.join(dir,"sales.json"));return{store,workflow:new SaleWorkflowEngine(store)}}
function readyForValidity(workflow){const sale=workflow.openAuthorizedSale({conversation_id:901,customer:{nombre:"Ana",curp:"CURP",nss:"NSS"},sale:{plan:"plan_2",precio:1500,authorized:true},documents:{files:[{id:"ine",type:"ine",name:"INE.pdf"},{id:"csf",type:"csf",name:"CSF.pdf"}]}});workflow.completeCapture(sale.sale_id);for(const key of["datos","alta","documentos","revision_final"])workflow.setValidationCheck(sale.sale_id,key,true,{by:"Validador"});return workflow.mustGet(sale.sale_id)}

test("vigencia solo inicia después de validación aprobada",()=>{const{workflow}=fixture();const sale=workflow.openAuthorizedSale({conversation_id:902,customer:{curp:"CURP",nss:"NSS"},sale:{authorized:true},documents:{files:[{id:"ine",type:"ine",name:"INE.pdf"},{id:"csf",type:"csf",name:"CSF.pdf"}]}});assert.throws(()=>workflow.confirmValidity(sale.sale_id,{document_name:"vigencia.pdf"}),/no permitido/i)});
test("confirmar vigencia exige documento",()=>{const{workflow}=fixture();const sale=readyForValidity(workflow);assert.throws(()=>workflow.confirmValidity(sale.sale_id,{by:"Vigencias"}),/documento de vigencia/i)});
test("vigencia confirmada registra responsable y libera pagos",()=>{const{workflow}=fixture();const sale=readyForValidity(workflow);const confirmed=workflow.confirmValidity(sale.sale_id,{document_name:"vigencia-ana.pdf",document_url:"https://example.test/vigencia.pdf",by:"Operador Vigencias"});assert.equal(confirmed.status,"validity_confirmed");assert.equal(confirmed.queue,"payment");assert.equal(confirmed.validity.confirmed,true);assert.equal(confirmed.validity.confirmed_by,"Operador Vigencias");assert.ok(confirmed.validity.confirmed_at);const payment=workflow.requestPayment(sale.sale_id,{by:"Cobranza"});assert.equal(payment.status,"payment_requested")});
test("incidencia de vigencia bloquea cobranza hasta reapertura y confirmación",()=>{const{workflow}=fixture();const sale=readyForValidity(workflow);const issue=workflow.reportValidityIssue(sale.sale_id,{reason:"IMSS todavía no refleja vigencia",by:"Vigencias"});assert.equal(issue.status,"validity_issue");assert.equal(issue.queue,"validity");assert.equal(issue.validity.issue.open,true);assert.throws(()=>workflow.requestPayment(sale.sale_id),/no permitido/i);const reopened=workflow.reopenValidity(sale.sale_id,{by:"Vigencias"});assert.equal(reopened.status,"waiting_validity");assert.equal(reopened.validity.issue,null);workflow.confirmValidity(sale.sale_id,{document_name:"vigencia.pdf",by:"Vigencias"});assert.equal(workflow.requestPayment(sale.sale_id).status,"payment_requested")});
test("sin vigencia confirmada nunca se puede solicitar pago",()=>{const{workflow}=fixture();const sale=readyForValidity(workflow);assert.throws(()=>workflow.requestPayment(sale.sale_id),/no permitido/i)});
test("sync documental no borra CURP o NSS existentes con valores null",()=>{const{workflow}=fixture();const sale=workflow.openAuthorizedSale({conversation_id:903,customer:{curp:"CURP-GUARDADA",nss:"12345678901"},sale:{authorized:true}});const synced=workflow.syncDocuments(sale.sale_id,{customer:{curp:null,nss:undefined},files:[]});assert.equal(synced.customer.curp,"CURP-GUARDADA");assert.equal(synced.customer.nss,"12345678901")});
