import test from "node:test";
import assert from "node:assert/strict";
import { deriveCommercialNeed, hasCommercialNeed, needGuardDecision, suppressRecommendationWithoutNeed } from "../src/sales/need-before-recommendation.js";

test("unemployment is activity context, not a commercial need",()=>{const n=deriveCommercialNeed("estoy desempleado");assert.equal(n.unknown,true);assert.equal(n.service_medical,false);assert.equal(n.afore_infonavit,false);});
test("medical service becomes explicit commercial need",()=>{const n=deriveCommercialNeed("lo quiero principalmente por el servicio médico");assert.equal(n.service_medical,true);assert.equal(n.unknown,false);});
test("AFORE and INFONAVIT become Plan 2 commercial need",()=>{const n=deriveCommercialNeed("también me interesa AFORE e INFONAVIT");assert.equal(n.afore_infonavit,true);assert.equal(n.unknown,false);});
test("need guard asks objective after basic qualification",()=>{const m={nombre:"Juan Pérez Martínez",primer_nombre:"Juan",edad:48,actividad:"desempleado",commercial_need:{unknown:true},sales_cycle:{authorized:false}};const d=needGuardDecision(m,"estoy desempleado");assert.ok(d);assert.equal(d.question_key,"necesidad_principal");assert.match(d.reply,/servicio médico/i);assert.match(d.reply,/semanas/i);assert.match(d.reply,/AFORE/i);assert.doesNotMatch(d.reply,/Plan 1|Plan 2|\$1,100|\$1,500/i);});
test("guard does not run before basic qualification is complete",()=>{const m={nombre:"Juan",edad:48,commercial_need:{unknown:true},sales_cycle:{authorized:false}};assert.equal(needGuardDecision(m,"hola"),null);});
test("guard does not run when need is already known",()=>{const m={nombre:"Juan",edad:48,actividad:"oficina",commercial_need:{service_medical:true,unknown:false},sales_cycle:{authorized:false}};assert.equal(hasCommercialNeed(m),true);assert.equal(needGuardDecision(m,"servicio médico"),null);});
test("LLM cannot recommend Plan 1 from unemployment alone",()=>{const m={nombre:"Juan",edad:48,actividad:"desempleado",commercial_need:{unknown:true},sales_cycle:{authorized:false}};const bad={reply:"Como estás desempleado, te recomiendo el Plan 1 por $1,100 MXN.",question_key:null};const d=suppressRecommendationWithoutNeed(bad,m,"estoy desempleado");assert.equal(d.question_key,"necesidad_principal");assert.doesNotMatch(d.reply,/te recomiendo el Plan 1/i);});
test("known commercial need permits recommendation",()=>{const m={commercial_need:{service_medical:true,unknown:false},sales_cycle:{authorized:false}};const good={reply:"Por lo que buscas, el Plan 1 puede ser una buena opción.",question_key:null};assert.deepEqual(suppressRecommendationWithoutNeed(good,m,"servicio médico"),good);});
