import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { SaleStore } from "../src/operations/sale-store.js";
import { SaleWorkflowEngine } from "../src/operations/workflow-engine.js";

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"martcom-payment-"));const store=new SaleStore(path.join(dir,"sales.json"));return{store,workflow:new SaleWorkflowEngine(store)}}
function ready(workflow){const sale=workflow.openAuthorizedSale({conversation_id:1001,customer:{nombre:"Ana",curp:"CURP",nss:"NSS"},sale:{plan:"plan_2",precio:1500,authorized:true},documents:{files:[{id:"ine",type:"ine",name:"INE.pdf"},{id:"csf",type:"csf",name:"CSF.pdf"}]}});workflow.completeCapture(sale.sale_id);for(const key of["datos","alta","documentos","revision_final"])workflow.setValidationCheck(sale.sale_id,key,true,{by:"Validación"});workflow.confirmValidity(sale.sale_id,{document_name:"vigencia.pdf",by:"Vigencias"});return workflow.mustGet(sale.sale_id)}

test("solicitud de pago registra responsable, método y monto del plan",()=>{const{workflow}=fixture();const sale=ready(workflow);const requested=workflow.requestPayment(sale.sale_id,{by:"Cobranza",method:"transferencia"});assert.equal(requested.status,"payment_requested");assert.equal(requested.payment.requested_by,"Cobranza");assert.equal(requested.payment.method,"transferencia");assert.equal(requested.payment.amount,1500)});
test("registrar pago exige comprobante o referencia documental",()=>{const{workflow}=fixture();const sale=ready(workflow);workflow.requestPayment(sale.sale_id,{by:"Cobranza"});assert.throws(()=>workflow.receivePayment(sale.sale_id,{reference:"ABC"}),/comprobante/i)});
test("pago recibido conserva comprobante, referencia y responsable",()=>{const{workflow}=fixture();const sale=ready(workflow);workflow.requestPayment(sale.sale_id,{by:"Cobranza"});const received=workflow.receivePayment(sale.sale_id,{proof_name:"pago.pdf",proof_url:"https://example.test/pago.pdf",reference:"REF-123",by:"Operador Cobranza"});assert.equal(received.status,"payment_received");assert.equal(received.payment.proof_name,"pago.pdf");assert.equal(received.payment.reference,"REF-123");assert.equal(received.payment.received_by,"Operador Cobranza")});
test("incidencia bloquea validación hasta reapertura",()=>{const{workflow}=fixture();const sale=ready(workflow);workflow.requestPayment(sale.sale_id);workflow.receivePayment(sale.sale_id,{proof_name:"pago.pdf"});const issue=workflow.reportPaymentIssue(sale.sale_id,{reason:"Monto no coincide",by:"Cobranza"});assert.equal(issue.status,"payment_issue");assert.equal(issue.payment.issue.open,true);assert.throws(()=>workflow.validatePayment(sale.sale_id),/no permitido/i);const reopened=workflow.reopenPayment(sale.sale_id,{by:"Cobranza"});assert.equal(reopened.status,"payment_received");assert.equal(reopened.payment.issue,null)});
test("validación de pago cierra formalmente expediente",()=>{const{workflow}=fixture();const sale=ready(workflow);workflow.requestPayment(sale.sale_id,{by:"Cobranza"});workflow.receivePayment(sale.sale_id,{proof_name:"pago.pdf",by:"Cobranza"});const completed=workflow.validatePayment(sale.sale_id,{by:"Supervisor Cobranza"});assert.equal(completed.status,"completed");assert.equal(completed.queue,"completed");assert.equal(completed.payment.validated,true);assert.equal(completed.payment.validated_by,"Supervisor Cobranza");assert.ok(completed.payment.validated_at);assert.ok(completed.completed_at)});
test("no se valida un pago sin comprobante persistido",()=>{const{workflow,store}=fixture();const sale=ready(workflow);workflow.requestPayment(sale.sale_id);const current=store.get(sale.sale_id);store.update(sale.sale_id,{status:"payment_received",payment:{...current.payment,received:true,proof_name:null,proof_url:null}},"test.corrupt",{});assert.throws(()=>workflow.validatePayment(sale.sale_id),/sin comprobante/i)});
