import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { SaleStore } from "../src/operations/sale-store.js";
import { SaleWorkflowEngine } from "../src/operations/workflow-engine.js";
import { classifyAttachment, documentPackageStatus } from "../src/operations/document-service.js";

function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"martcom-next-"));const store=new SaleStore(path.join(dir,"sales.json"));return{store,workflow:new SaleWorkflowEngine(store)};}
function completeInput(){return { conversation_id:101, customer:{nombre:"Ana",curp:"AAAA000000AAAAAA00",nss:"12345678901"}, sale:{plan:"plan_2",precio:1500,authorized:true}, documents:{files:[{id:"ine",type:"ine",name:"INE.pdf"},{id:"csf",type:"csf",name:"Constancia Situacion Fiscal.pdf"}]}};}
function createSale(workflow,input=completeInput()){return workflow.openAuthorizedSale(input);}

test("classifies common MARTCOM documents",()=>{assert.equal(classifyAttachment({file_name:"INE_frente.pdf"}),"ine");assert.equal(classifyAttachment({file_name:"Constancia Situacion Fiscal.pdf"}),"csf");});
test("document package reports missing requirements",()=>{const status=documentPackageStatus({customer:{curp:"X",nss:null},documents:{files:[{type:"ine"}]}});assert.equal(status.complete,false);assert.deepEqual(status.missing.sort(),["csf","nss"]);});
test("authorized sale enters capture queue with complete checklist",()=>{const{workflow}=fixture();const sale=createSale(workflow);assert.equal(sale.status,"waiting_capture");assert.equal(sale.queue,"capture");assert.equal(sale.documents.complete,true);});
test("capture cannot complete with missing CURP NSS INE or CSF",()=>{const{workflow}=fixture();const sale=createSale(workflow,{conversation_id:102,customer:{nombre:"Luis"},sale:{plan:"plan_1",authorized:true}});assert.equal(sale.documents.complete,false);assert.throws(()=>workflow.completeCapture(sale.sale_id),/documental incompleto/i);});
test("document sync can complete an initially incomplete expediente",()=>{const{workflow}=fixture();const sale=createSale(workflow,{conversation_id:103,customer:{nombre:"Luis"},sale:{plan:"plan_1",authorized:true}});const synced=workflow.syncDocuments(sale.sale_id,{customer:{curp:"CURP",nss:"NSS"},files:[{id:"1",type:"ine",name:"ine.pdf"},{id:"2",type:"csf",name:"csf.pdf"}]});assert.equal(synced.documents.complete,true);assert.deepEqual(synced.documents.missing,[]);});
test("capture completion sends complete expediente to validation",()=>{const{workflow}=fixture();const sale=createSale(workflow);workflow.startCapture(sale.sale_id,{id:5,name:"Capturista"});const updated=workflow.completeCapture(sale.sale_id);assert.equal(updated.status,"waiting_validation");assert.equal(updated.queue,"validation");});
test("validation requires all four checks",()=>{const{workflow}=fixture();const sale=createSale(workflow);workflow.completeCapture(sale.sale_id);workflow.setValidationCheck(sale.sale_id,"datos",true);workflow.setValidationCheck(sale.sale_id,"alta",true);workflow.setValidationCheck(sale.sale_id,"documentos",true);const before=workflow.setValidationCheck(sale.sale_id,"revision_final",false);assert.equal(before.status,"validation_in_progress");const approved=workflow.setValidationCheck(sale.sale_id,"revision_final",true);assert.equal(approved.validation.approved,true);assert.equal(approved.status,"waiting_validity");});
test("cannot confirm validity before validation approval",()=>{const{workflow}=fixture();const sale=createSale(workflow);assert.throws(()=>workflow.confirmValidity(sale.sale_id,{document_name:"vigencia.pdf"}),/no permitido/i);});
test("full workflow reaches completed in strict order",()=>{const{workflow}=fixture();const sale=createSale(workflow);workflow.startCapture(sale.sale_id,{name:"Capturista"});workflow.completeCapture(sale.sale_id);for(const key of["datos","alta","documentos","revision_final"])workflow.setValidationCheck(sale.sale_id,key,true);workflow.confirmValidity(sale.sale_id,{document_name:"vigencia.pdf"});workflow.requestPayment(sale.sale_id);workflow.receivePayment(sale.sale_id);const completed=workflow.validatePayment(sale.sale_id);assert.equal(completed.status,"completed");assert.equal(completed.payment.validated,true);});
test("sale store persists expediente across restart",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"martcom-next-persist-"));const file=path.join(dir,"sales.json");const store1=new SaleStore(file);const workflow=new SaleWorkflowEngine(store1);const sale=createSale(workflow);const store2=new SaleStore(file);assert.equal(store2.get(sale.sale_id).customer.nombre,"Ana");assert.equal(store2.get(sale.sale_id).documents.complete,true);});
