import test from "node:test";
import assert from "node:assert/strict";
import { analyzeAutonomousSale, recommendPlan, salesInstruction } from "../src/sales/autonomous-sales-engine.js";
const base={tiene_imss:false,edad:50,necesidad_principal:"afiliacion_imss",intereses:{imss:true,semanas_cotizadas:true},necesidades:["semanas_cotizadas"],sales_cycle:{stage:"qualified",authorized:false}};
test("recomienda plan base para IMSS y semanas",()=>assert.equal(recommendPlan(base).id,"plan_base"));
test("recomienda Plan 2 cuando busca AFORE",()=>assert.equal(recommendPlan({...base,intereses:{afore:true}}).id,"plan_2"));
test("autorización explícita activa handoff",()=>{const r=analyzeAutonomousSale("Sí, quiero iniciar el trámite",base);assert.equal(r.authorized,true);assert.equal(r.shouldHandoff,true);assert.equal(r.stage,"authorized")});
test("pensarlo no activa handoff",()=>assert.equal(analyzeAutonomousSale("Déjame pensarlo",base).shouldHandoff,false));
test("objeción de precio entra a objection_handling",()=>assert.equal(analyzeAutonomousSale("¿Cuánto cuesta?",base).stage,"objection_handling"));
test("instrucción comercial bloquea CURP como requisito",()=>assert.match(salesInstruction(base),/CURP\/NSS/));
test("instrucción comercial ordena handoff en autorización persistida",()=>assert.match(salesInstruction({...base,sales_cycle:{stage:"authorized",authorized:true}}),/handoff=true/));
