export function inspectorPage() {
  return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MARTCOM AI Inspector</title>
<style>
:root{font-family:Inter,system-ui,Segoe UI,sans-serif;color:#172033;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}.top{background:#111827;color:#fff;padding:18px 24px;display:flex;align-items:center;justify-content:space-between}.brand{font-size:20px;font-weight:800}.sub{font-size:12px;opacity:.75}.wrap{max-width:1300px;margin:auto;padding:22px}.toolbar{display:flex;gap:10px;margin-bottom:18px}.toolbar input{flex:1;padding:12px;border:1px solid #d6deea;border-radius:10px}.toolbar button{padding:12px 18px;border:0;border-radius:10px;background:#2563eb;color:#fff;font-weight:700;cursor:pointer}.grid{display:grid;grid-template-columns:300px 1fr;gap:18px}.card{background:#fff;border:1px solid #e3e9f2;border-radius:14px;box-shadow:0 5px 18px rgba(15,23,42,.05);overflow:hidden}.card h2{font-size:15px;margin:0;padding:15px 17px;border-bottom:1px solid #edf1f6}.list{max-height:70vh;overflow:auto}.item{padding:13px 16px;border-bottom:1px solid #edf1f6;cursor:pointer}.item:hover,.item.active{background:#eff6ff}.item strong{display:block}.item small{color:#64748b}.content{padding:18px}.stats{display:grid;grid-template-columns:repeat(4,minmax(120px,1fr));gap:12px;margin-bottom:16px}.stat{background:#f8fafc;border:1px solid #e5eaf1;border-radius:10px;padding:12px}.stat b{display:block;font-size:18px;margin-top:4px}.cols{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{border:1px solid #e5eaf1;border-radius:10px;overflow:hidden}.panel h3{font-size:14px;margin:0;padding:11px 13px;background:#f8fafc;border-bottom:1px solid #e5eaf1}.panel .inner{padding:13px}.row{display:grid;grid-template-columns:170px 1fr;gap:8px;padding:6px 0;border-bottom:1px dashed #edf1f6}.key{font-weight:700;color:#475569}.timeline{max-height:420px;overflow:auto}.event{border-left:3px solid #2563eb;padding:8px 10px;margin:8px 0;background:#f8fafc;border-radius:0 8px 8px 0}.event time{font-size:11px;color:#64748b}.event strong{display:block;margin:3px 0}pre{white-space:pre-wrap;word-break:break-word;background:#0f172a;color:#dbeafe;padding:14px;border-radius:9px;max-height:420px;overflow:auto;font-size:12px}.empty{padding:45px;text-align:center;color:#64748b}.ok{color:#22c55e}.bad{color:#ef4444}@media(max-width:900px){.grid,.cols{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr}.list{max-height:260px}}
</style></head><body>
<div class="top"><div><div class="brand">MARTCOM AI Inspector</div><div class="sub">Inspector 1.1 · Intent Engine · Solo lectura</div></div><div id="health">Introduce el token</div></div>
<div class="wrap"><div class="toolbar"><input id="token" type="password" placeholder="Token privado del Inspector"><input id="conversation" placeholder="ID de conversación"><button onclick="openConversation()">Abrir</button></div>
<div class="grid"><div class="card"><h2>Conversaciones registradas</h2><div id="list" class="list"><div class="empty">Introduce el token para consultar.</div></div></div><div class="card"><h2>Expediente de conversación</h2><div id="content" class="content"><div class="empty">Selecciona una conversación.</div></div></div></div></div>
<script>
var active=null;function el(id){return document.getElementById(id)}function esc(v){return String(v==null?'No informado':v).replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}function token(){return el('token').value.trim()}
async function api(path){var r=await fetch(path,{headers:{'x-inspector-token':token()}});if(!r.ok){var d=await r.json().catch(function(){return {}});throw new Error(d.error||('HTTP '+r.status))}return r.json()}
function row(k,v){return '<div class="row"><div class="key">'+esc(k)+'</div><div>'+esc(v)+'</div></div>'}
async function loadHealth(){try{var d=await api('/inspector/api/health');el('health').innerHTML='<span class="ok">● Sistema activo</span> · '+esc(d.version)}catch(e){el('health').innerHTML='<span class="bad">● Sin acceso</span>'}}
async function loadList(){try{var d=await api('/inspector/api/conversations');if(!d.items.length){el('list').innerHTML='<div class="empty">Aún no hay conversaciones guardadas.</div>';return}el('list').innerHTML=d.items.map(function(x){return '<div class="item '+(x.id===active?'active':'')+'" onclick="show('+x.id+')"><strong>#'+x.id+' · '+esc(x.nombre||'Sin nombre')+'</strong><small>'+esc(x.intent||x.necesidad||'Sin intención')+' · '+esc(x.actualizado_en||'')+'</small></div>'}).join('')}catch(e){el('list').innerHTML='<div class="empty bad">'+esc(e.message)+'</div>'}}
async function show(id){active=id;el('conversation').value=id;await loadList();el('content').innerHTML='<div class="empty">Cargando…</div>';try{var d=await api('/inspector/api/conversations/'+id),m=d.memory,p=m.flujo||{},s=m.ventas||{};var events=d.timeline.length?d.timeline.map(function(e){return '<div class="event"><time>'+esc(new Date(e.timestamp).toLocaleString())+'</time><strong>'+esc(e.type)+'</strong><div>'+esc(JSON.stringify(e.details))+'</div></div>'}).join(''):'Sin eventos registrados todavía.';el('content').innerHTML='<div class="stats"><div class="stat">Intención<b>'+esc((m.intent||{}).label||(m.intent||{}).id)+'</b></div><div class="stat">Confianza<b>'+esc((m.intent||{}).confidence!=null?Math.round((m.intent||{}).confidence*100)+'%':'No informado')+'</b></div><div class="stat">Fase<b>'+esc(p.fase)+'</b></div><div class="stat">Siguiente paso<b>'+esc(p.siguiente_paso)+'</b></div></div><div class="cols"><div class="panel"><h3>Perfil del cliente</h3><div class="inner">'+row('Nombre',m.nombre)+row('Edad',m.edad)+row('Actividad',m.actividad)+row('IMSS actual',m.tiene_imss===true?'Sí':m.tiene_imss===false?'No':'No informado')+row('Necesidad',m.necesidad_principal)+row('Última cotización',m.ultima_cotizacion)+row('AFORE',m.afore_actual)+row('Asesor presentación',m.asesor_presentacion)+row('Intención',(m.intent||{}).label||(m.intent||{}).id)+row('Prioridad',(m.intent||{}).priority)+row('Evidencia',((m.intent||{}).evidence||[]).join(', '))+'</div></div><div class="panel"><h3>Estado del motor</h3><div class="inner">'+row('Última pregunta',m.ultima_pregunta)+row('Presentación realizada',m.presentacion_realizada?'Sí':'No')+row('CURP recibida',m.curp_recibida?'Sí':'No')+row('NSS recibido',m.nss_recibido?'Sí':'No')+row('Problema comercial',s.problema)+row('Eventos registrados',d.timeline.length)+'</div></div><div class="panel"><h3>Timeline</h3><div class="inner timeline">'+events+'</div></div><div class="panel"><h3>Memoria JSON</h3><div class="inner"><pre>'+esc(JSON.stringify(m,null,2))+'</pre></div></div></div>'}catch(e){el('content').innerHTML='<div class="empty bad">'+esc(e.message)+'</div>'}}
function openConversation(){var id=Number(el('conversation').value);if(id)show(id)}el('token').addEventListener('change',function(){loadHealth();loadList()});
</script></body></html>`;
}
