export function operationsPage() {
  return `<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MARTCOM Next Operations</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color:#18212f;background:#f5f7fb}*{box-sizing:border-box}body{margin:0}.top{background:#111827;color:white;padding:18px 24px}.top h1{margin:0;font-size:20px}.top small{color:#9ca3af}.wrap{padding:20px;max-width:1500px;margin:auto}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.tabs button{border:1px solid #d6dbe5;background:white;padding:9px 14px;border-radius:9px;cursor:pointer}.tabs button.active{background:#111827;color:white}.stats{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:12px;margin-bottom:18px}.stat,.card{background:white;border:1px solid #e2e7ef;border-radius:12px;box-shadow:0 2px 8px #1118270a}.stat{padding:14px}.stat b{font-size:24px;display:block}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:14px}.card{padding:16px}.row{display:flex;justify-content:space-between;gap:10px}.pill{font-size:12px;padding:4px 8px;border-radius:999px;background:#eef2ff}.muted{color:#6b7280;font-size:13px}.checks{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:12px 0}.checks label{font-size:13px}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.actions button{border:0;background:#1f2937;color:white;padding:8px 10px;border-radius:8px;cursor:pointer}.actions button.secondary{background:#e5e7eb;color:#111827}.empty{padding:40px;text-align:center;color:#6b7280;background:white;border-radius:12px}@media(max-width:800px){.stats{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}}
</style></head>
<body><div class="top"><h1>MARTCOM Next Operations</h1><small>Captura · Validación · Vigencia · Pagos · Realtime</small></div>
<div class="wrap"><div class="tabs" id="tabs"></div><div class="stats" id="stats"></div><div class="grid" id="grid"></div></div>
<script>
const queues=[['all','Todo'],['capture','Captura'],['validation','Validación'],['validity','Vigencias'],['payment','Pagos'],['completed','Completados']];let active='all',sales=[];
const token=new URLSearchParams(location.search).get('token')||localStorage.getItem('nextOpsToken')||'';if(token)localStorage.setItem('nextOpsToken',token);
const headers={'content-type':'application/json','x-operations-token':token};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function render(){tabs.innerHTML=queues.map(([q,n])=>'<button class="'+(active===q?'active':'')+'" onclick="active=\''+q+'\';render()">'+n+'</button>').join('');const counts=Object.fromEntries(queues.slice(1).map(([q])=>[q,sales.filter(s=>s.queue===q).length]));stats.innerHTML=queues.slice(1).map(([q,n])=>'<div class="stat"><span class="muted">'+n+'</span><b>'+counts[q]+'</b></div>').join('');const list=active==='all'?sales:sales.filter(s=>s.queue===active);grid.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No hay expedientes en esta cola.</div>'}
function card(s){const checks=['datos','alta','documentos','revision_final'].map(k=>'<label><input type="checkbox" '+(s.validation?.[k]?'checked':'')+' onchange="check(\''+s.sale_id+'\',\''+k+'\',this.checked)"> '+k.replace('_',' ')+'</label>').join('');let actions='';if(s.queue==='capture')actions='<button onclick="startCapture(\''+s.sale_id+'\')">Tomar</button><button onclick="completeCapture(\''+s.sale_id+'\')">Alta procesada</button>';if(s.queue==='validity')actions='<button onclick="validity(\''+s.sale_id+'\')">Confirmar vigencia</button>';if(s.queue==='payment'&&s.status==='validity_confirmed')actions='<button onclick="paymentRequest(\''+s.sale_id+'\')">Solicitar pago</button>';if(s.queue==='payment'&&s.status==='payment_requested')actions='<button onclick="paymentReceive(\''+s.sale_id+'\')">Pago recibido</button>';if(s.queue==='payment'&&s.status==='payment_received')actions='<button onclick="paymentValidate(\''+s.sale_id+'\')">Validar pago</button>';return '<article class="card"><div class="row"><b>'+esc(s.sale_id)+'</b><span class="pill">'+esc(s.status)+'</span></div><h3>'+esc(s.customer?.nombre||'Cliente sin nombre')+'</h3><div class="muted">Chat #'+esc(s.conversation_id||'-')+' · '+esc(s.sale?.plan||'Sin plan')+' · $'+esc(s.sale?.precio||'-')+'</div>'+(s.queue==='validation'?'<div class="checks">'+checks+'</div>':'')+'<div class="actions">'+actions+'</div></article>'}
async function api(url,method='GET',body){const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'Error');return j}
async function load(){try{sales=(await api('/operations/api/sales')).items;render()}catch(e){grid.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
async function act(url,body={}){try{await api(url,'POST',body);await load()}catch(e){alert(e.message)}}
function startCapture(id){act('/operations/api/sales/'+id+'/capture/start',{name:'Capturista'})}function completeCapture(id){act('/operations/api/sales/'+id+'/capture/complete',{})}function check(id,key,checked){act('/operations/api/sales/'+id+'/validation/check',{key,checked})}function validity(id){const name=prompt('Nombre o referencia del documento de vigencia:');if(name)act('/operations/api/sales/'+id+'/validity/confirm',{document_name:name})}function paymentRequest(id){act('/operations/api/sales/'+id+'/payment/request')}function paymentReceive(id){act('/operations/api/sales/'+id+'/payment/receive')}function paymentValidate(id){act('/operations/api/sales/'+id+'/payment/validate')}
const es=new EventSource('/operations/api/events?token='+encodeURIComponent(token));es.onmessage=()=>load();load();
</script></body></html>`;
}
