export function operationsPage() {
  return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MARTCOM Next Operations V2</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,sans-serif;color:#172033;background:#f4f6fa}*{box-sizing:border-box}body{margin:0}.top{background:#101827;color:white;padding:18px 24px}.top h1{margin:0;font-size:21px}.top small{color:#aab3c3}.wrap{max-width:1500px;margin:auto;padding:20px}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-bottom:15px}.search{flex:1;min-width:240px;border:1px solid #d8dee8;background:#fff;border-radius:10px;padding:10px 12px}.select{border:1px solid #d8dee8;background:#fff;border-radius:10px;padding:10px 12px}.tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:16px}.tabs button{border:1px solid #d8dee8;background:white;padding:8px 12px;border-radius:9px;cursor:pointer}.tabs button.active{background:#172033;color:white}.stats{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:10px;margin-bottom:16px}.stat,.card{background:#fff;border:1px solid #e1e6ef;border-radius:13px;box-shadow:0 3px 12px #1118270a}.stat{padding:13px}.stat small{color:#778195}.stat b{font-size:22px;display:block;margin-top:3px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(340px,1fr));gap:13px}.card{padding:16px}.row{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.card h3{margin:12px 0 4px}.muted{color:#778195;font-size:13px}.pill{font-size:11px;padding:5px 8px;border-radius:999px;background:#eef2ff;font-weight:650}.pill.ok{background:#e7f8ee;color:#17663a}.pill.bad{background:#fff0f0;color:#9b2c2c}.pill.warn{background:#fff7df;color:#805600}.requirements{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin:13px 0}.req{text-align:center;padding:7px 3px;border-radius:8px;background:#f1f3f7;font-size:11px}.req.yes{background:#e7f8ee;color:#17663a}.req.no{background:#fff0f0;color:#9b2c2c}.missing{font-size:12px;background:#fff8e7;color:#805600;padding:8px;border-radius:8px;margin-bottom:10px}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.btn{border:0;background:#1f2937;color:white;padding:8px 10px;border-radius:8px;cursor:pointer;text-decoration:none;font-size:12px}.btn.secondary{background:#e8ebf0;color:#172033}.btn:disabled{opacity:.4;cursor:not-allowed}.empty{padding:45px;text-align:center;background:white;border-radius:13px;color:#778195}.capture-banner{padding:12px 14px;background:#eef2ff;border-radius:11px;margin-bottom:14px;font-size:13px}.progress{height:5px;background:#e5e7eb;border-radius:99px;overflow:hidden;margin:10px 0}.progress span{display:block;height:100%;background:#334155}.count{font-size:12px;color:#778195;margin-left:auto}@media(max-width:800px){.stats{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.requirements{grid-template-columns:1fr 1fr}}
</style></head><body>
<div class="top"><h1>MARTCOM Next Operations V2</h1><small>Mesa de Captura · Expedientes · Validación · Vigencia · Pagos · Realtime</small></div>
<div class="wrap"><div class="toolbar"><input id="search" class="search" placeholder="Buscar por nombre, CURP, NSS, teléfono, chat o expediente…"><select id="docs" class="select"><option value="all">Todos los expedientes</option><option value="complete">Documentación completa</option><option value="incomplete">Documentación incompleta</option></select><span id="count" class="count"></span></div><div class="tabs" id="tabs"></div><div class="stats" id="stats"></div><div id="banner"></div><div class="grid" id="grid"></div></div>
<script>
const queues=[['all','Todo'],['capture','Captura'],['validation','Validación'],['validity','Vigencias'],['payment','Pagos'],['completed','Completados']];let active=new URLSearchParams(location.search).get('queue')||'capture',sales=[],query='',docFilter='all';
const token=new URLSearchParams(location.search).get('token')||localStorage.getItem('nextOpsToken')||'';if(token)localStorage.setItem('nextOpsToken',token);const headers={'content-type':'application/json','x-operations-token':token};
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function money(v){return v==null?'—':new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(v)}
function filtered(){return sales.filter(s=>(active==='all'||s.queue===active)&&(docFilter==='all'||(docFilter==='complete'?s.documents?.complete===true:s.documents?.complete!==true))&&(!query||[s.sale_id,s.customer?.nombre,s.customer?.curp,s.customer?.nss,s.customer?.telefono,s.conversation_id].some(v=>String(v||'').toLowerCase().includes(query))))}
function render(){tabs.innerHTML=queues.map(([q,n])=>'<button class="'+(active===q?'active':'')+'" onclick="active=\''+q+'\';render()">'+n+'</button>').join('');const counts=Object.fromEntries(queues.slice(1).map(([q])=>[q,sales.filter(s=>s.queue===q).length]));stats.innerHTML=queues.slice(1).map(([q,n])=>'<div class="stat"><small>'+n+'</small><b>'+counts[q]+'</b></div>').join('');const list=filtered();count.textContent=list.length+' expediente'+(list.length===1?'':'s');banner.innerHTML=active==='capture'?'<div class="capture-banner"><b>Mesa de Captura:</b> “Alta procesada” solo se habilita cuando CURP, NSS, INE y Constancia de Situación Fiscal están completos.</div>':'';grid.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No hay expedientes con estos filtros.</div>'}
function card(s){const reqs=s.documents?.checklist?.requirements||[];const complete=Boolean(s.documents?.complete);const pct=Math.round(((s.documents?.checklist?.received_count||0)/(s.documents?.checklist?.required_count||4))*100);const reqHtml=reqs.map(r=>'<div class="req '+(r.received?'yes':'no')+'">'+(r.received?'✓ ':'✕ ')+esc(r.key.toUpperCase())+'</div>').join('');let actions='<a class="btn secondary" href="/operations/sales/'+encodeURIComponent(s.sale_id)+'?token='+encodeURIComponent(token)+'">Abrir expediente</a>';if(s.queue==='capture'){if(s.status==='waiting_capture')actions+='<button class="btn" onclick="startCapture(\''+s.sale_id+'\')">Tomar</button>';actions+='<button class="btn" '+(!complete?'disabled':'')+' onclick="completeCapture(\''+s.sale_id+'\')">Alta procesada</button>'}if(s.queue==='validation')actions+='<span class="pill warn">Requiere validación</span>';if(s.queue==='validity')actions+='<span class="pill warn">Esperando vigencia</span>';if(s.queue==='payment')actions+='<span class="pill warn">Etapa de pago</span>';return '<article class="card"><div class="row"><b>'+esc(s.sale_id)+'</b><span class="pill '+(complete?'ok':'bad')+'">'+(complete?'COMPLETO':'INCOMPLETO')+'</span></div><h3>'+esc(s.customer?.nombre||'Cliente sin nombre')+'</h3><div class="muted">Chat #'+esc(s.conversation_id||'—')+' · '+esc(s.sale?.plan||'Sin plan')+' · '+money(s.sale?.precio)+'</div><div class="progress"><span style="width:'+pct+'%"></span></div><div class="requirements">'+reqHtml+'</div>'+(!complete?'<div class="missing"><b>Falta:</b> '+esc((s.documents?.missing||[]).join(', ')||'requisitos')+'</div>':'')+'<div class="muted">Estado: '+esc(String(s.status||'').replaceAll('_',' '))+' · Responsable: '+esc(s.capture?.assigned_name||'Sin asignar')+'</div><div class="actions">'+actions+'</div></article>'}
async function api(url,method='GET',body){const r=await fetch(url,{method,headers,body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'Error');return j}async function load(){try{sales=(await api('/operations/api/sales')).items;render()}catch(e){grid.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}async function act(url,body={}){try{await api(url,'POST',body);await load()}catch(e){alert(e.message)}}function startCapture(id){act('/operations/api/sales/'+id+'/capture/start',{name:'Capturista'})}function completeCapture(id){act('/operations/api/sales/'+id+'/capture/complete',{})}
search.addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();render()});docs.addEventListener('change',e=>{docFilter=e.target.value;render()});const es=new EventSource('/operations/api/events?token='+encodeURIComponent(token));es.onmessage=()=>load();load();
</script></body></html>`;
}
