export const SALE_STATUSES = Object.freeze({
  AUTHORIZED:"authorized",WAITING_CAPTURE:"waiting_capture",CAPTURE_IN_PROGRESS:"capture_in_progress",ALTA_PROCESSED:"alta_processed",WAITING_VALIDATION:"waiting_validation",VALIDATION_IN_PROGRESS:"validation_in_progress",VALIDATION_APPROVED:"validation_approved",VALIDATION_REJECTED:"validation_rejected",WAITING_VALIDITY:"waiting_validity",VALIDITY_CONFIRMED:"validity_confirmed",PAYMENT_REQUESTED:"payment_requested",PAYMENT_RECEIVED:"payment_received",PAYMENT_VALIDATED:"payment_validated",COMPLETED:"completed",ALTA_ISSUE:"alta_issue",VALIDITY_ISSUE:"validity_issue",PAYMENT_ISSUE:"payment_issue",CANCELLED:"cancelled",
});
export const VALIDATION_KEYS=Object.freeze(["datos","alta","documentos","revision_final"]);
function requireStatus(sale,allowed,action){if(!allowed.includes(sale.status))throw new Error(`${action} no permitido desde estado ${sale.status}`)}
function requireReason(payload){const reason=String(payload?.reason||payload?.notes||"").trim();if(!reason)throw new Error("Se requiere indicar el motivo");return reason}

export class SaleWorkflowEngine{
  constructor(store){this.store=store}
  openAuthorizedSale(input){const existing=input.conversation_id?this.store.findByConversationId(input.conversation_id):null;if(existing)return existing;return this.store.create({...input,status:SALE_STATUSES.WAITING_CAPTURE,queue:"capture"})}
  syncDocuments(id,payload={}){return this.store.syncDocuments(id,payload)}
  startCapture(id,operator={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_CAPTURE],"Iniciar captura");return this.store.update(id,{status:SALE_STATUSES.CAPTURE_IN_PROGRESS,queue:"capture",capture:{...sale.capture,assigned_to:operator.id||null,assigned_name:operator.name||null,started_at:new Date().toISOString()}},"capture.started",operator)}
  completeCapture(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.CAPTURE_IN_PROGRESS,SALE_STATUSES.WAITING_CAPTURE],"Completar alta");if(!sale.documents?.complete)throw new Error(`Expediente documental incompleto. Faltan: ${(sale.documents?.missing||[]).join(", ")||"requisitos"}`);return this.store.update(id,{status:SALE_STATUSES.WAITING_VALIDATION,queue:"validation",capture:{...sale.capture,completed_at:new Date().toISOString(),notes:payload.notes??sale.capture.notes},validation:{...sale.validation,datos:false,alta:false,documentos:false,revision_final:false,approved:false,approved_at:null,correction:null,rejected:false}},"capture.completed",{notes:payload.notes||""})}
  setValidationCheck(id,key,checked,payload={}){if(!VALIDATION_KEYS.includes(key))throw new Error("Check de validación inválido");const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDATION,SALE_STATUSES.VALIDATION_IN_PROGRESS],"Validar expediente");const validation={...sale.validation,[key]:Boolean(checked),notes:payload.notes??sale.validation.notes,reviewed_by:payload.by||sale.validation?.reviewed_by||null,correction:null,rejected:false};const allChecked=VALIDATION_KEYS.every(item=>validation[item]===true);if(allChecked){validation.approved=true;validation.approved_at=new Date().toISOString();return this.store.update(id,{status:SALE_STATUSES.WAITING_VALIDITY,queue:"validity",validation},"validation.approved",{by:payload.by||null})}validation.approved=false;validation.approved_at=null;return this.store.update(id,{status:SALE_STATUSES.VALIDATION_IN_PROGRESS,queue:"validation",validation},"validation.check.updated",{key,checked:Boolean(checked),by:payload.by||null})}
  requestCorrection(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDATION,SALE_STATUSES.VALIDATION_IN_PROGRESS,SALE_STATUSES.VALIDATION_REJECTED],"Solicitar corrección");const reason=requireReason(payload);const target=payload.target==="customer"?"customer":"capture";const correction={target,reason,requested_by:payload.by||null,requested_at:new Date().toISOString(),open:true};const validation={...sale.validation,approved:false,approved_at:null,correction,rejected:false,notes:reason};if(target==="customer")return this.store.update(id,{status:SALE_STATUSES.WAITING_CAPTURE,queue:"capture",validation,capture:{...sale.capture,completed_at:null,notes:`Corrección solicitada por Validación: ${reason}`}},"validation.correction.requested",correction);return this.store.update(id,{status:SALE_STATUSES.CAPTURE_IN_PROGRESS,queue:"capture",validation,capture:{...sale.capture,completed_at:null,notes:`Corrección solicitada por Validación: ${reason}`}},"validation.correction.requested",correction)}
  rejectValidation(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDATION,SALE_STATUSES.VALIDATION_IN_PROGRESS],"Rechazar validación");const reason=requireReason(payload);const validation={...sale.validation,approved:false,approved_at:null,rejected:true,rejected_at:new Date().toISOString(),rejected_by:payload.by||null,notes:reason,correction:null};return this.store.update(id,{status:SALE_STATUSES.VALIDATION_REJECTED,queue:"validation",validation},"validation.rejected",{reason,by:payload.by||null})}
  reopenRejected(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.VALIDATION_REJECTED],"Reabrir validación");const validation={...sale.validation,rejected:false,rejected_at:null,rejected_by:null,notes:payload.notes||sale.validation.notes};return this.store.update(id,{status:SALE_STATUSES.VALIDATION_IN_PROGRESS,queue:"validation",validation},"validation.reopened",payload)}
  confirmValidity(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDITY],"Confirmar vigencia");if(!payload.document_url&&!payload.document_name)throw new Error("Se requiere referencia al documento de vigencia");return this.store.update(id,{status:SALE_STATUSES.VALIDITY_CONFIRMED,queue:"payment",validity:{confirmed:true,document_url:payload.document_url||null,document_name:payload.document_name||null,confirmed_at:new Date().toISOString(),notes:payload.notes||""}},"validity.confirmed",{document_name:payload.document_name||null})}
  requestPayment(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.VALIDITY_CONFIRMED],"Solicitar pago");return this.store.update(id,{status:SALE_STATUSES.PAYMENT_REQUESTED,queue:"payment",payment:{...sale.payment,requested:true,requested_at:new Date().toISOString(),notes:payload.notes||sale.payment.notes}},"payment.requested",payload)}
  receivePayment(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.PAYMENT_REQUESTED],"Registrar pago");return this.store.update(id,{status:SALE_STATUSES.PAYMENT_RECEIVED,queue:"payment",payment:{...sale.payment,received:true,received_at:new Date().toISOString(),notes:payload.notes||sale.payment.notes}},"payment.received",payload)}
  validatePayment(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.PAYMENT_RECEIVED],"Validar pago");return this.store.update(id,{status:SALE_STATUSES.COMPLETED,queue:"completed",payment:{...sale.payment,validated:true,validated_at:new Date().toISOString(),notes:payload.notes||sale.payment.notes}},"payment.validated",payload)}
  mustGet(id){const sale=this.store.get(id);if(!sale)throw new Error("Expediente no encontrado");return sale}
}
