export const SALE_STATUSES = Object.freeze({
  AUTHORIZED:"authorized",WAITING_CAPTURE:"waiting_capture",CAPTURE_IN_PROGRESS:"capture_in_progress",ALTA_PROCESSED:"alta_processed",WAITING_VALIDATION:"waiting_validation",VALIDATION_IN_PROGRESS:"validation_in_progress",VALIDATION_APPROVED:"validation_approved",VALIDATION_REJECTED:"validation_rejected",WAITING_VALIDITY:"waiting_validity",VALIDITY_CONFIRMED:"validity_confirmed",PAYMENT_REQUESTED:"payment_requested",PAYMENT_RECEIVED:"payment_received",PAYMENT_VALIDATED:"payment_validated",COMPLETED:"completed",ALTA_ISSUE:"alta_issue",VALIDITY_ISSUE:"validity_issue",PAYMENT_ISSUE:"payment_issue",CANCELLED:"cancelled",
});
export const VALIDATION_KEYS=Object.freeze(["datos","alta","documentos","revision_final"]);
function requireStatus(sale,allowed,action){if(!allowed.includes(sale.status))throw new Error(`${action} no permitido desde estado ${sale.status}`)}
function requireReason(payload){const reason=String(payload?.reason||payload?.notes||"").trim();if(!reason)throw new Error("Se requiere indicar el motivo");return reason}
function proofFrom(payload={}){return {proof_url:payload.proof_url||payload.document_url||null,proof_name:payload.proof_name||payload.document_name||null}}

export class SaleWorkflowEngine{
  constructor(store){this.store=store}
  openAuthorizedSale(input){const existing=input.conversation_id?this.store.findByConversationId(input.conversation_id):null;if(existing)return existing;return this.store.create({...input,status:SALE_STATUSES.WAITING_CAPTURE,queue:"capture"})}
  syncDocuments(id,payload={}){return this.store.syncDocuments(id,payload)}
  startCapture(id,operator={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_CAPTURE],"Iniciar captura");return this.store.update(id,{status:SALE_STATUSES.CAPTURE_IN_PROGRESS,queue:"capture",capture:{...sale.capture,assigned_to:operator.id||null,assigned_name:operator.name||null,started_at:new Date().toISOString()}},"capture.started",operator)}
  completeCapture(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.CAPTURE_IN_PROGRESS,SALE_STATUSES.WAITING_CAPTURE],"Completar alta");if(!sale.documents?.complete)throw new Error(`Expediente documental incompleto. Faltan: ${(sale.documents?.missing||[]).join(", ")||"requisitos"}`);return this.store.update(id,{status:SALE_STATUSES.WAITING_VALIDATION,queue:"validation",capture:{...sale.capture,completed_at:new Date().toISOString(),notes:payload.notes??sale.capture.notes},validation:{...sale.validation,datos:false,alta:false,documentos:false,revision_final:false,approved:false,approved_at:null,correction:null,rejected:false}},"capture.completed",{notes:payload.notes||""})}
  setValidationCheck(id,key,checked,payload={}){if(!VALIDATION_KEYS.includes(key))throw new Error("Check de validación inválido");const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDATION,SALE_STATUSES.VALIDATION_IN_PROGRESS],"Validar expediente");const validation={...sale.validation,[key]:Boolean(checked),notes:payload.notes??sale.validation.notes,reviewed_by:payload.by||sale.validation?.reviewed_by||null,correction:null,rejected:false};const allChecked=VALIDATION_KEYS.every(item=>validation[item]===true);if(allChecked){validation.approved=true;validation.approved_at=new Date().toISOString();return this.store.update(id,{status:SALE_STATUSES.WAITING_VALIDITY,queue:"validity",validation,validity:{...sale.validity,confirmed:false,issue:null}},"validation.approved",{by:payload.by||null})}validation.approved=false;validation.approved_at=null;return this.store.update(id,{status:SALE_STATUSES.VALIDATION_IN_PROGRESS,queue:"validation",validation},"validation.check.updated",{key,checked:Boolean(checked),by:payload.by||null})}
  requestCorrection(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDATION,SALE_STATUSES.VALIDATION_IN_PROGRESS,SALE_STATUSES.VALIDATION_REJECTED],"Solicitar corrección");const reason=requireReason(payload);const target=payload.target==="customer"?"customer":"capture";const correction={target,reason,requested_by:payload.by||null,requested_at:new Date().toISOString(),open:true};const validation={...sale.validation,approved:false,approved_at:null,correction,rejected:false,notes:reason};if(target==="customer")return this.store.update(id,{status:SALE_STATUSES.WAITING_CAPTURE,queue:"capture",validation,capture:{...sale.capture,completed_at:null,notes:`Corrección solicitada por Validación: ${reason}`}},"validation.correction.requested",correction);return this.store.update(id,{status:SALE_STATUSES.CAPTURE_IN_PROGRESS,queue:"capture",validation,capture:{...sale.capture,completed_at:null,notes:`Corrección solicitada por Validación: ${reason}`}},"validation.correction.requested",correction)}
  rejectValidation(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDATION,SALE_STATUSES.VALIDATION_IN_PROGRESS],"Rechazar validación");const reason=requireReason(payload);const validation={...sale.validation,approved:false,approved_at:null,rejected:true,rejected_at:new Date().toISOString(),rejected_by:payload.by||null,notes:reason,correction:null};return this.store.update(id,{status:SALE_STATUSES.VALIDATION_REJECTED,queue:"validation",validation},"validation.rejected",{reason,by:payload.by||null})}
  reopenRejected(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.VALIDATION_REJECTED],"Reabrir validación");const validation={...sale.validation,rejected:false,rejected_at:null,rejected_by:null,notes:payload.notes||sale.validation.notes};return this.store.update(id,{status:SALE_STATUSES.VALIDATION_IN_PROGRESS,queue:"validation",validation},"validation.reopened",payload)}
  reportValidityIssue(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDITY],"Reportar incidencia de vigencia");const reason=requireReason(payload);const issue={reason,reported_by:payload.by||null,reported_at:new Date().toISOString(),open:true};return this.store.update(id,{status:SALE_STATUSES.VALIDITY_ISSUE,queue:"validity",validity:{...sale.validity,confirmed:false,issue,notes:reason}},"validity.issue",issue)}
  reopenValidity(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.VALIDITY_ISSUE],"Reabrir vigencia");return this.store.update(id,{status:SALE_STATUSES.WAITING_VALIDITY,queue:"validity",validity:{...sale.validity,confirmed:false,issue:null,notes:payload.notes||sale.validity?.notes||""}},"validity.reopened",{by:payload.by||null})}
  confirmValidity(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.WAITING_VALIDITY],"Confirmar vigencia");if(sale.validation?.approved!==true)throw new Error("No se puede confirmar vigencia sin validación aprobada");if(!payload.document_url&&!payload.document_name)throw new Error("Se requiere referencia al documento de vigencia");const confirmedAt=new Date().toISOString();return this.store.update(id,{status:SALE_STATUSES.VALIDITY_CONFIRMED,queue:"payment",validity:{...sale.validity,confirmed:true,document_url:payload.document_url||null,document_name:payload.document_name||null,confirmed_at:confirmedAt,confirmed_by:payload.by||null,issue:null,notes:payload.notes||""}},"validity.confirmed",{document_name:payload.document_name||null,document_url:payload.document_url||null,by:payload.by||null,confirmed_at:confirmedAt})}
  requestPayment(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.VALIDITY_CONFIRMED],"Solicitar pago");if(sale.validity?.confirmed!==true||!sale.validity?.confirmed_at)throw new Error("No se puede solicitar pago sin vigencia confirmada");const requestedAt=new Date().toISOString();return this.store.update(id,{status:SALE_STATUSES.PAYMENT_REQUESTED,queue:"payment",payment:{...sale.payment,requested:true,requested_at:requestedAt,requested_by:payload.by||null,method:payload.method||sale.payment?.method||null,amount:payload.amount??sale.sale?.precio??sale.payment?.amount??null,issue:null,notes:payload.notes||sale.payment?.notes||""}},"payment.requested",{by:payload.by||null,method:payload.method||null,amount:payload.amount??sale.sale?.precio??null})}
  receivePayment(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.PAYMENT_REQUESTED],"Registrar pago");const proof=proofFrom(payload);if(!proof.proof_url&&!proof.proof_name)throw new Error("Se requiere comprobante o referencia del pago");const receivedAt=new Date().toISOString();return this.store.update(id,{status:SALE_STATUSES.PAYMENT_RECEIVED,queue:"payment",payment:{...sale.payment,received:true,received_at:receivedAt,received_by:payload.by||null,reference:payload.reference||null,...proof,issue:null,notes:payload.notes||sale.payment?.notes||""}},"payment.received",{by:payload.by||null,reference:payload.reference||null,...proof})}
  reportPaymentIssue(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.PAYMENT_REQUESTED,SALE_STATUSES.PAYMENT_RECEIVED],"Reportar incidencia de pago");const reason=requireReason(payload);const issue={reason,reported_by:payload.by||null,reported_at:new Date().toISOString(),open:true,previous_status:sale.status};return this.store.update(id,{status:SALE_STATUSES.PAYMENT_ISSUE,queue:"payment",payment:{...sale.payment,issue,notes:reason}},"payment.issue",issue)}
  reopenPayment(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.PAYMENT_ISSUE],"Reabrir pago");const previous=sale.payment?.issue?.previous_status===SALE_STATUSES.PAYMENT_RECEIVED?SALE_STATUSES.PAYMENT_RECEIVED:SALE_STATUSES.PAYMENT_REQUESTED;return this.store.update(id,{status:previous,queue:"payment",payment:{...sale.payment,issue:null,notes:payload.notes||sale.payment?.notes||""}},"payment.reopened",{by:payload.by||null,status:previous})}
  validatePayment(id,payload={}){const sale=this.mustGet(id);requireStatus(sale,[SALE_STATUSES.PAYMENT_RECEIVED],"Validar pago");if(sale.payment?.received!==true)throw new Error("No existe pago recibido para validar");if(!sale.payment?.proof_url&&!sale.payment?.proof_name)throw new Error("No se puede validar pago sin comprobante");if(sale.payment?.issue?.open)throw new Error("Existe una incidencia de pago abierta");const validatedAt=new Date().toISOString();return this.store.update(id,{status:SALE_STATUSES.COMPLETED,queue:"completed",payment:{...sale.payment,validated:true,validated_at:validatedAt,validated_by:payload.by||null,issue:null,notes:payload.notes||sale.payment?.notes||""},completed_at:validatedAt},"payment.validated",{by:payload.by||null,validated_at:validatedAt})}
  mustGet(id){const sale=this.store.get(id);if(!sale)throw new Error("Expediente no encontrado");return sale}
}
