import express from "express";
import { fileURLToPath } from "node:url";
import { inspectorPage } from "./inspector/page.js";
import { buildAlerts, dashboardStats, explainDecision, filterConversations, summarizeConversation, uniqueFilterOptions } from "./inspector/inspector-service.js";
import { buildDiagnostics } from "./inspector/diagnostics-service.js";
import { conversationProgress, handoffMetrics, rotationOverview, slotStates } from "./inspector/operations-service.js";
import { conversationIdOf, inboxIdOf, isContact, isIncoming, messageOf, messagesOf } from "./utils/conversation.js";
import { buildAnalytics } from "./inspector/analytics-service.js";

export function createRouter({ config, memories, buffer, inspectorEvents, handoffRotation, operationsConfig }) {
  const router = express.Router();
  const inspectorPublicPath = fileURLToPath(new URL("./inspector/public/", import.meta.url));
  router.use("/inspector/assets", express.static(inspectorPublicPath,{fallthrough:false,maxAge:"5m",etag:true}));
  const inspectorAuthorized=req=>Boolean(config.inspector.token)&&(req.get("x-inspector-token")===config.inspector.token||req.query.token===config.inspector.token);
  const inspectorAdminAuthorized=req=>Boolean(config.inspector.adminToken)&&req.get("x-inspector-admin-token")===config.inspector.adminToken;
  router.get("/inspector",(_req,res)=>res.type("html").send(inspectorPage()));
  router.get("/inspector/api/health",(req,res)=>{if(!inspectorAuthorized(req))return res.status(401).json({error:"Token del Inspector inválido"});const diagnostics=buildDiagnostics({config,memories,inspectorEvents});res.json({status:"ok",overall:diagnostics.overall,version:"3.4.0",inspectorVersion:"1.7",architecture:"modular",autonomousSales:true,lastEventAt:inspectorEvents.stats?.().lastEventAt||null,autoHandoff:config.handoff.enabled,diagnostics})});
  router.get("/inspector/api/dashboard",(req,res)=>{if(!inspectorAuthorized(req))return res.status(401).json({error:"Token del Inspector inválido"});const all=(typeof memories.list==="function"?memories.list():Object.entries(memories.data||{}).map(([id])=>({id:Number(id),...memories.get(Number(id))}))).filter(m=>Number.isFinite(Number(m.id))).map(m=>summarizeConversation(m,inspectorEvents.get(Number(m.id)),m.id)),events=typeof inspectorEvents.listAll==="function"?inspectorEvents.listAll():[],filtered=filterConversations(all,req.query,config.ai.timezone),ids=new Set(filtered.map(x=>Number(x.id))),filteredEvents=events.filter(e=>ids.has(Number(e.conversationId)));res.json({stats:dashboardStats(filtered,filteredEvents),filters:uniqueFilterOptions(all),handoffs:handoffMetrics(filtered),rotations:rotationOverview(config,handoffRotation,operationsConfig),range:{from:req.query.from||null,to:req.query.to||null}})});
  router.get("/inspector/api/diagnostics",(req,res)=>{if(!inspectorAuthorized(req))return res.status(401).json({error:"Token del Inspector inválido"});res.json(buildDiagnostics({config,memories,inspectorEvents}))});
  router.get("/inspector/api/conversations",(req,res)=>{if(!inspectorAuthorized(req))return res.status(401).json({error:"Token del Inspector inválido"});const all=typeof memories.list==="function"?memories.list():Object.entries(memories.data||{}).map(([id])=>({id:Number(id),...memories.get(Number(id))})),items=all.filter(m=>Number.isFinite(Number(m.id))).map(m=>summarizeConversation(m,inspectorEvents.get(Number(m.id)),m.id));res.json({items:filterConversations(items,req.query,config.ai.timezone)})});
  router.get("/inspector/api/conversations/:conversationId",(req,res)=>{if(!inspectorAuthorized(req))return res.status(401).json({error:"Token del Inspector inválido"});const id=Number(req.params.conversationId);if(!id)return res.status(400).json({error:"conversation_id inválido"});const memory=memories.get(id),timeline=inspectorEvents.get(id);res.json({conversationId:id,memory,timeline,alerts:buildAlerts(memory,timeline),explanation:explainDecision(memory,timeline),diagnostics:buildDiagnostics({config,memories,inspectorEvents}),progress:conversationProgress(memory),slots:slotStates(memory),rotations:rotationOverview(config,handoffRotation,operationsConfig)})});
  router.get("/inspector/api/analytics",(req,res)=>{if(!inspectorAuthorized(req))return res.status(401).json({error:"Token del Inspector inválido"});try{return res.json(buildAnalytics({memories:typeof memories.list==="function"?memories.list():[],events:inspectorEvents?.listAll?inspectorEvents.listAll():[],from:req.query.from||null,to:req.query.to||null,timezone:config.ai.timezone}))}catch(error){console.error("Analytics error:",error);return res.status(500).json({error:"No se pudo generar Analytics",detail:error.message})}});
  router.get("/inspector/api/control/rotations",(req,res)=>{if(!inspectorAuthorized(req))return res.status(401).json({error:"Token del Inspector inválido"});const state=operationsConfig.snapshot();res.json({adminEnabled:Boolean(config.inspector.adminToken),groups:state.groups,agents:operationsConfig.allAgents(),exceptions:state.exceptions,audit:(state.audit||[]).slice().reverse().slice(0,100),rotations:rotationOverview(config,handoffRotation,operationsConfig)})});
  router.put("/inspector/api/control/rotations/:group",express.json(),async(req,res)=>{if(!inspectorAdminAuthorized(req))return res.status(401).json({error:"Token administrador inválido"});try{return res.json({ok:true,state:await operationsConfig.setGroup(req.params.group,req.body?.agents,"inspector-admin")})}catch(error){return res.status(400).json({error:error.message})}});
  router.post("/inspector/api/control/agents",express.json(),async(req,res)=>{if(!inspectorAdminAuthorized(req))return res.status(401).json({error:"Token administrador inválido"});try{return res.json({ok:true,state:await operationsConfig.addMasterAgent({id:req.body?.id,name:req.body?.name},"inspector-admin")})}catch(error){return res.status(400).json({error:error.message})}});
  router.post("/inspector/api/control/agents/remove",express.json(),async(req,res)=>{if(!inspectorAdminAuthorized(req))return res.status(401).json({error:"Token administrador inválido"});try{return res.json({ok:true,state:await operationsConfig.removeAgentFromGroup(req.body?.group,req.body?.agentId,"inspector-admin")})}catch(error){return res.status(400).json({error:error.message})}});
  router.delete("/inspector/api/control/agents/:id",async(req,res)=>{if(!inspectorAdminAuthorized(req))return res.status(401).json({error:"Token administrador inválido"});try{return res.json({ok:true,state:await operationsConfig.deleteMasterAgent(req.params.id,"inspector-admin")})}catch(error){return res.status(400).json({error:error.message})}});
  router.post("/inspector/api/control/agents/move",express.json(),async(req,res)=>{if(!inspectorAdminAuthorized(req))return res.status(401).json({error:"Token administrador inválido"});try{return res.json({ok:true,state:await operationsConfig.moveAgent({sourceGroup:req.body?.sourceGroup,targetGroup:req.body?.targetGroup,agentId:req.body?.agentId},"inspector-admin")})}catch(error){return res.status(400).json({error:error.message})}});
  router.post("/inspector/api/control/agents/copy",express.json(),async(req,res)=>{if(!inspectorAdminAuthorized(req))return res.status(401).json({error:"Token administrador inválido"});try{return res.json({ok:true,state:await operationsConfig.copyAgent({targetGroup:req.body?.targetGroup,agentId:req.body?.agentId},"inspector-admin")})}catch(error){return res.status(400).json({error:error.message})}});
  router.put("/inspector/api/control/exceptions/:date",express.json(),async(req,res)=>{if(!inspectorAdminAuthorized(req))return res.status(401).json({error:"Token administrador inválido"});try{return res.json({ok:true,state:await operationsConfig.setException(req.params.date,req.body?.agents,"inspector-admin")})}catch(error){return res.status(400).json({error:error.message})}});
  router.delete("/inspector/api/control/exceptions/:date",async(req,res)=>{if(!inspectorAdminAuthorized(req))return res.status(401).json({error:"Token administrador inválido"});try{return res.json({ok:true,state:await operationsConfig.deleteException(req.params.date,"inspector-admin")})}catch(error){return res.status(400).json({error:error.message})}});
  router.get("/",(_req,res)=>res.json({service:"martcom-ai-sales-intelligence",version:"3.4.0",inspector_version:"1.7",status:"ok",architecture:"modular",autonomous_sales:true,memory_file:config.storage.memoryFile,rotation_file:config.storage.rotationFile,handoff_rotation_file:config.storage.handoffRotationFile,intro_agents:config.ai.introAgents,auto_handoff:config.handoff.enabled,handoff_sunday_agents:config.handoff.sundayAgents,handoff_saturday_agents:config.handoff.saturdayAgents,handoff_weekday_agents:config.handoff.weekdayAgents,message_buffer_ms:config.ai.bufferMs,schedule:`${config.ai.startHour}:00-${config.ai.endHour}:00 ${config.ai.timezone}`,inbox_id:config.chatwoot.inboxId,agent_id:config.chatwoot.agentId}));
  router.get("/health",(_req,res)=>res.json({status:"ok",version:"3.4.0",inspectorVersion:"1.7",timestamp:new Date().toISOString()}));
  router.get("/memory/:conversationId",(req,res)=>{const id=Number(req.params.conversationId);if(!id)return res.status(400).json({error:"conversation_id inválido"});res.json(memories.get(id))});
  router.delete("/memory/:conversationId",async(req,res)=>{if(config.webhookSecret&&req.query.secret!==config.webhookSecret)return res.status(401).json({error:"unauthorized"});const id=Number(req.params.conversationId);if(!id)return res.status(400).json({error:"conversation_id inválido"});await memories.clear(id);res.json({deleted:true,conversationId:id})});
  router.post("/webhook/chatwoot",(req,res)=>{if(config.webhookSecret&&req.query.secret!==config.webhookSecret)return res.status(401).json({error:"unauthorized"});res.status(200).json({received:true});const event=String(req.body?.event||""),id=conversationIdOf(req.body);if(!id)return;if(event==="message_created"){const message=messageOf(req.body);if(!message?.id||inboxIdOf(req.body)!==config.chatwoot.inboxId||!isIncoming(message)||message.private===true||!isContact(message))return;buffer.enqueue(id,message,"message_created",req.body)}else if(event==="conversation_updated"){const conversation=req.body?.conversation||req.body,inbox=Number(conversation?.inbox_id||conversation?.inbox?.id||inboxIdOf(req.body)),agent=Number(conversation?.meta?.assignee?.id||conversation?.assignee?.id||req.body?.assignee?.id);if(inbox&&inbox!==config.chatwoot.inboxId)return;if(agent&&agent!==config.chatwoot.agentId)return;const messages=messagesOf(conversation);for(let index=messages.length-1;index>=0;index--){const message=messages[index];if(message&&isIncoming(message)&&!message.private&&isContact(message)){buffer.enqueue(id,message,"conversation_updated",req.body);return}}console.log(`Actualización ${id} recibida sin mensaje entrante utilizable; no se consulta Chatwoot.`)}});
  return router;
}
